# Generated by Django 5.0.1 on 2024-02-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(blank=True, max_length=255, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Phone', models.CharField(blank=True, max_length=11, null=True)),
                ('Email', models.CharField(blank=True, max_length=255, null=True)),
                ('AnimeCharacter', models.CharField(blank=True, max_length=255, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Quality', models.CharField(blank=True, max_length=255, null=True)),
                ('ShippingMethod', models.CharField(blank=True, max_length=255, null=True)),
                ('TotalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Information', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.CharField(blank=True, max_length=255, null=True)),
                ('Password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
